#ifndef CONFIG_INSTRUCTIONS_H
#define CONFIG_INSTRUCTIONS_H

#define INSTRUCTION_SLIDER_LEFT '1'
#define INSTRUCTION_SLIDER_RIGHT '2'
#define INSTRUCTION_STOP '3'
#define INSTRUCTION_SET_HOME '4'
#define INSTRUCTION_SPEED_UP '5'
#define INSTRUCTION_SPEED_DOWN '6'

#define INSTRUCTION_SET_SPEED_INCREMENT '!'

#define INSTRUCTION_SET_HALF_STEP '7'
#define INSTRUCTION_SET_QUARTER_STEP '8'
#define INSTRUCTION_SET_EIGHTH_STEP '9'
#define INSTRUCTION_SET_SIXTEENTH_STEP '0'




#endif